### ISSUE TITLE
Spreadsheet gem dependency error while installing plugin

### ISSUE THREAD

**Issue by lajish** [aspiresoftware/redmine-import-tasks#1]
Hi there,

Please find the message which i found while installing plugin 

C:\Windows\system32> cd C:\Redmine\Bitnami-Redmine\apps\redmine\htdocs\plugins
C:\Redmine\Bitnami-Redmine\apps\redmine\htdocs\plugins> bundle exec rake redmine:plugins NAME=issue_importer_xls RAIL
S_ENV=production
You cannot specify the same gem twice with different version requirements.
You specified: spreadsheet (~> 0.9.7) and spreadsheet (>= 0)

**Comment by guruprasad1** [comment]
It seems like that you have installed some other plugins as well that have spreadsheet gem dependency.
You can resolve it two ways:
- Find the plugin which has spreadsheet gem dependency and add spreadsheet gem version in its Gemfile
  - E.g  gem 'spreadsheet',"~> 0.9.7"
- Change the Gemfile of issue_import_xls plugin by following way
  - gem 'spreadsheet'

**Comment by lajish** [comment]
Hi there,

Thanks for your suggestion. Let me check this and will get back to you soon.

**Comment by lajish** [comment]
Hi,
It worked...!!!
Actually I was using issues xls export plugin. Once again thanks for your valuable suggestion.

One more thing, is there any possibility to create a plugin which can inherit/import issue categories across all project ?
